Update jvm-function-invoker buildpack

diff --git a/buildpacks/jvm-function-invoker/bin/build b/buildpacks/jvm-function-invoker/bin/build
--- a/buildpacks/jvm-function-invoker/bin/build
+++ b/buildpacks/jvm-function-invoker/bin/build
@@ -19,37 +19,126 @@ source "${CNB_BUILDPACK_DIR}/common-lib/jvm_buildpack_utils.sh"
 # Export environment variables
 ########################################################################################################################
 export_env_vars=()
-export_env_vars+=("JVM_INVOKER_JAR_URL")
 export_env_vars+=("HEROKU_BUILDPACK_DEBUG")
 
 bputils::export_env "${platform_dir}" "${export_env_vars[@]}"
 
 ########################################################################################################################
-# Download Invoker
+# Install Java function runtime
 ########################################################################################################################
-log::cnb::header "Installing JVM function invoker"
-log::cnb::debug "Preparing JVM invoker layer"
-invoker_layer_dir="${layers_dir}/jvm-invoker"
-invoker_layer_toml="${invoker_layer_dir}.toml"
-mkdir -p "${invoker_layer_dir}"
+log::cnb::header "Installing Java function runtime"
 
-cat >"${invoker_layer_toml}" <<-EOF
+runtime_jar_url="$(yj -t <"${CNB_BUILDPACK_DIR}/buildpack.toml" | jq -r ".metadata.runtime.url")"
+runtime_jar_sha256="$(yj -t <"${CNB_BUILDPACK_DIR}/buildpack.toml" | jq -r ".metadata.runtime.sha256")"
+
+runtime_layer_dir="${layers_dir}/sf-fx-runtime-java"
+runtime_layer_jar_path="${runtime_layer_dir}/runtime.jar"
+runtime_layer_toml="${runtime_layer_dir}.toml"
+
+cached_layer_runtime_jar_sha256=""
+if [[ -f "${runtime_layer_toml}" ]]; then
+	cached_layer_runtime_jar_sha256=$(yj -t <"${runtime_layer_toml}" | jq -r ".metadata.runtime_jar_sha256 // empty")
+fi
+
+if [[ "${cached_layer_runtime_jar_sha256}" == "${runtime_jar_sha256}" && -f "${runtime_layer_jar_path}" ]]; then
+	log::cnb::info "Installed Java function runtime from cache"
+else
+	log::cnb::debug "Creating function runtime layer"
+	runtime_layer_dir="${layers_dir}/sf-fx-runtime-java"
+	runtime_layer_toml="${runtime_layer_dir}.toml"
+	mkdir -p "${runtime_layer_dir}"
+
+	cat >"${runtime_layer_toml}" <<-EOF
+		launch = true
+		build = false
+		cache = true
+
+		[metadata]
+		runtime_jar_url = "${runtime_jar_url}"
+		runtime_jar_sha256 = "${runtime_jar_sha256}"
+	EOF
+	log::cnb::debug "Function runtime layer successfully created"
+
+	log::cnb::info "Starting download of function runtime"
+	if ! bputils::download_file "${runtime_jar_url}" "${runtime_layer_jar_path}"; then
+		log::cnb::error "Download of function runtime failed" <<-EOF
+			We couldn't download the function runtime at "${runtime_jar_url}".
+			This is usually caused by intermittent network issues. Please try again and contact us should the error persist.
+		EOF
+		exit 1
+	fi
+	log::cnb::info "Function runtime download successful"
+
+	if ! bputils::check_sha256 "${runtime_layer_jar_path}" "${runtime_jar_sha256}"; then
+		log::cnb::error "Function runtime integrity check failed" <<-EOF
+			We could not verify the integrity of the downloaded function runtime.
+			Please try again and contact us should the error persist.
+		EOF
+		exit 1
+	fi
+
+	log::cnb::info "Function runtime installation successful"
+fi
+
+########################################################################################################################
+# Bundle function
+########################################################################################################################
+log::cnb::header "Detecting function"
+
+function_bundle_layer_dir="${layers_dir}/function-bundle"
+function_bundle_toml="${function_bundle_layer_dir}.toml"
+mkdir -p "${function_bundle_layer_dir}"
+
+cat >"${function_bundle_toml}" <<-EOF
 	launch = true
-	build = true
+	build = false
 	cache = false
 EOF
 
-path_to_invoker_jar="${invoker_layer_dir}/invoker.jar"
-log::cnb::info "Downloading invoker JAR file: ${JVM_INVOKER_JAR_URL}"
-if ! bputils::download_file "${JVM_INVOKER_JAR_URL:-}" "${path_to_invoker_jar}"; then
-	log::cnb::error "Download of invoker JAR file failed" <<-EOF
-		You have set JVM_INVOKER_JAR_URL to "${JVM_INVOKER_JAR_URL}". We tried to download the file at this
-		URL, but the download failed. Please verify that the given URL is correct and try again.
+{
+	java -jar "${runtime_layer_jar_path}" bundle "${app_dir}" "${function_bundle_layer_dir}"
+	bundle_exit_code="${?}"
+} || true
+
+case "${bundle_exit_code}" in
+0) log::cnb::info "Detection successful" ;;
+1)
+	log::cnb::error "No functions found" <<-EOF
+		Your project does not seem to contain any Java functions.
+		The output above might contain information about issues with your function.
 	EOF
 	exit 1
-fi
+	;;
+2)
+	log::cnb::error "Multiple functions found" <<-EOF
+		Your project contains multiple Java functions.
+		Currently, only projects that contain exactly one (1) function are supported.
+	EOF
+	exit 1
+	;;
+3 | 4 | 5 | 6)
+	log::cnb::error "Detection failed" <<-EOF
+		Function detection failed with internal error "${bundle_exit_code}".
+	EOF
+	exit 1
+	;;
 
-log::cnb::info "Invoker installation successful!"
+*)
+	log::cnb::error "Detection failed" <<-EOF
+		Function detection failed with unexpected error code ${bundle_exit_code}.
+		The output above might contain hints what caused this error to happen.
+	EOF
+	exit 1
+	;;
+esac
+
+########################################################################################################################
+# Log function info
+########################################################################################################################
+bundle_toml="${function_bundle_layer_dir}/function-bundle.toml"
+log::cnb::header "Detected function: $(yj -t <"${bundle_toml}" | jq -r ".function.class")"
+log::cnb::info "Payload type: $(log::cnb::bold "$(yj -t <"${bundle_toml}" | jq -r ".function.payload_class")")"
+log::cnb::info "Return type: $(log::cnb::bold "$(yj -t <"${bundle_toml}" | jq -r ".function.return_class")")"
 
 ########################################################################################################################
 # Generate launch.toml
@@ -57,5 +146,5 @@ log::cnb::info "Invoker installation successful!"
 cat >>"${layers_dir}/launch.toml" <<-EOF
 	[[processes]]
 	type = "web"
-	command = "java -jar ${path_to_invoker_jar} ${app_dir}"
+	command = "java -jar ${runtime_layer_jar_path} serve ${function_bundle_layer_dir}"
 EOF
